name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/install/cache
          key: ${{ runner.os }}-test-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test:ci
